DATABASE_STEAM_LENGTH = 128

INTERVAL_DAY = 0
INTERVAL_WEEK = 1
INTERVAL_MONTH = 2
INTERVAL_YEAR = 3

g_Intervals = {
	[INTERVAL_DAY] = "day",
	[INTERVAL_WEEK] = "week",
	[INTERVAL_MONTH] = "month",
	[INTERVAL_YEAR] = "year",
	["day"] = INTERVAL_DAY,
	["week"] = INTERVAL_WEEK,
	["month"] = INTERVAL_MONTH,
	["year"] = INTERVAL_YEAR
}